# Generated by Django 4.1.7 on 2023-03-21 21:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80283d80-e3a9-4cc7-90ac-e883c047f79e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
