# Generated by Django 4.1.7 on 2023-03-21 21:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todomodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9296bbc2-22e5-40e6-9bc7-11d087a503c3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
