# Generated by Django 4.1.7 on 2023-03-21 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todomodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='id',
            field=models.AutoField(auto_created=True, default=uuid.UUID('5fecb70a-e5aa-469e-b047-f3353202f89b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
